name: Terraform plan

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment type"
        required: true
        type: string
        default: "dev"


env:
  PLAN: plan-dev.tfplan
  TF_IN_AUTOMATION: "true"
  GIT_STRATEGY: fetch # can be clone if the CICD fails on a cached repository
  AUTOAPPLY: ""

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  plan:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.3.6
    steps:
      - uses: actions/checkout@v2

      - name: Compute short sha
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo "Short SHA\:\ ${SHORT_SHA}"

      - name: Terraform init
        run: |
          echo "setup ${{ inputs.environment }}"
          set -x
          chmod -R a+rX,og-w .
          terraform version
          terraform init -upgrade
          terraform init -lock=false
          terraform workspace select ${{ inputs.environment }}
          set +x

      - name: Download built react app
        uses: actions/download-artifact@v3
        with:
          name: plan-${SHORT_SHA}
          path: plan

      - name: Terraform apply
        run: |
            echo "apply ${{ inputs.environment }}"
            terraform apply -parallelism=50 -input=false ${PLAN}
